# Generated by Django 3.2.9 on 2021-11-02 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('org_id', models.IntegerField(default=794778)),
                ('template_file', models.FileField(upload_to='pdf_templates')),
                ('coords_x', models.IntegerField(blank=True, null=True)),
                ('coords_y', models.IntegerField(blank=True, null=True)),
                ('color_r', models.IntegerField(default=0)),
                ('color_g', models.IntegerField(default=0)),
                ('color_b', models.IntegerField(default=0)),
                ('event_year', models.IntegerField(default=0)),
                ('event_month', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'queued'), (1, 'created'), (2, 'sent'), (3, 'failed')], db_index=True, default=0, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('url', models.URLField(blank=True, max_length=250, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person', to='badges.person')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template', to='badges.badgetemplate')),
            ],
        ),
    ]
