# Generated by Django 3.2.9 on 2021-11-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_badgetemplate_subdirectory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(fields=('template', 'person'), name='unique_badge'),
        ),
    ]
