# Generated by Django 3.2.9 on 2022-06-24 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_models_help_text'),
        ('badges', '0004_auto_20220624_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='email_template',
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='email_template',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post_office.emailtemplate'),
        ),
    ]
