# Generated by Django 3.2.9 on 2022-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_alter_badgetemplate_coords_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetemplate',
            name='orientation',
            field=models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], default='P', max_length=1),
        ),
    ]
